# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMTZOv0W0wbgR1EQP7MdHO_hd4MkJztF
"""

print('olá mundo')

msg = 'olá mundo'
print(msg)

nome = input('qual seu nome?').lower()
print('seja bem-vindo, {}!'.format (nome))

idade = input('Agora digite sua idade: ')
print('sua idade é: {} Anos'.format (idade))

estado_civil = input("Qual seu estado civil? ")
if estado_civil == 'casado':
  print('está casado')
elif estado_civil == 'solteiro':
  print('Precisa arrumar uma namorada')
elif estado_civil == 'divorciado':
  print('que pena!')
else:
  print('nao tem essa opção')

salario_mes = int(input('Qual seu salário mensal ?'))
print('seu salario mensal é: R$', salario_mes)

horas_trabalhadas = int(input('Quantas horas você trabalha por semana?'))
print(horas_trabalhadas, 'horas semanais')

horas_trabalhadas_mes = horas_trabalhadas * 4
print('você trabalha aproximadamente', horas_trabalhadas_mes, 'horas por mês')

valor_hora = salario_mes / horas_trabalhadas
print('você ganha por hora: R$', valor_hora)

#variaveis

#numeros
velocidade_internet = 10
print(velocidade_internet)

#float
nota_filme = 8.5

#valores booleanos
esta_aberto = False or True

#String
nome_aluno = 'jhonatan sumback'

#laços de repetição

for palavra in range(1,4):
  print('carregando')

for item in range(1,20,2):
  print(item)

nomes = ['jhonatan', 'camila', 'rodrigo']
for nome in nomes:
  print(nome)

#imprima os valores de 1 a N

valor_maximo = int(input('digite o valor máximo'))
valor_inicial = 1
for numero in range(valor_inicial, valor_maximo + 1):
  print(numero)

#coleçoes (listas)
#         0   1   2
precos = [20,50,200]
print(precos[2])
print(precos.index(200))

#idades = [15,46,75,34,23]
#total = 0
#loop idade em idades
#total = total + idade
#print total

idades = [15,46,75,34,23]
total = 0
for idade in idades:
  total = total + idade
print(total)

numero = int(input('digite um numero'))
if numero > 0:
  fatorial = 1
  for item in range(1,numero + 1):
    fatorial = fatorial * item
print(fatorial)

#input valor_aleatorio de 1 a 10
#input chute
#if chute > valor_aleatorio:
#print chute maior que valo gerado
#if chute < valor_aleatorio
#print chute foi menor
#if chute = valor_aleatorio
#print vc acertou

import random

valor_aleatorio = random.randint(1,10)

acertou = False
while acertou == False:
  chute = int(input('chute um valor de 1 a 10: '))
  if chute > valor_aleatorio:
    print('chute foi maior que valor gerado')
  elif chute < valor_aleatorio:
    print('chute foi menor que valor gerado')
  elif chute == valor_aleatorio:
    acertou = True
    print('vc acertou')

#mostrando o tipo de variável
x = (4)
y = 'teste'

print(type(x))
print(type(y))

#desconpactando
frutas = ['laranja', 'maca', 'uva']

x = y = z = frutas
print(x)
print(y)
print(z)

#variáveis dentro e fora de funções

x = "global"

def myfunc():
   x = "dentro da função"
   print('minha função é: ' + x)

myfunc()

print("fora da função é: " + x)

#função global

def myfunc():
  global x
  x = 'função global'

myfunc()

print('x agora pode usar dentro e fora da func: ' + x)

import random


print(random.randrange(1,10))

#strings em python


a = "ola mundo"
print(len(a))

texto = "noite o dia está muito calor"
if "hoje" in texto:
  print("sim, 'hoje' está presente na frase")
elif "hoje" not in texto:
  print("não, não tem essa palavra no texto")

#combinar string com números (f)
idade = 30
txt = f"minha idade é {idade}"
print(txt)

txt = f"o valor de {20 * 2} é :"
print(txt)

txt = "teste com caractere usando \"aspas\" duplas com outras aspas duplas"
print(txt)

a = 200
b = 33

if b > a:
  print("b é maior que a")
else:
  print("b não é maior que a")

x = "olá"
y = -2

print(bool(x))
print(bool(y))

def myfuncion():
  return True

if myfuncion():
  print("sim")

else:
  print("não")

x = 2.5
print(isinstance(x, int))

#listas de python / add item na lista

thislist = ["apple", "banana", "cherry"]
thislist[1:3] = ["watermelon"]
print(thislist)

#imprime cada item da lista um por um

lista1 = ["maçã", "Banana", "uva","Pera" ]
lista2 = [1, 5, 7, 9, 3, 10, 24]


for x in lista1:
  print(x)
lista1.sort(key = str.lower)
print(lista1)

def myfunc(n):
  return abs(n - 50)

thislist = [100, 50, 65, 82, 23]
thislist.sort(key = myfunc)
print(thislist)

#tupas de acesso

tuplas = ('amora', 'morango', 'banana')
if 'amor' in tuplas:
  print('sim, tem amora na tupla')
else:
  print('não tem')

fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

print(fruits)

categoria = input("digite a categoria do produto: ")
nome_produto = input("digite o nome do produto: ")
qnt_atual = input("digite a quantidade atual: ")

if categoria and nome_produto and qnt_atual:
  if categoria == 'alimentos':
    if qnt_atual < 75:
      print(f'solicitar {nome_produto} à equipe de compras, temos apenas {qnt_atual} unidades em estoque')

    elif categoria == 'bebidas':
      if qnt_atual < 50:
        print(f'solicitar {nome_produtos} a equipe de compras, temos apenas {qnt_atual} em estoque')

    elif categoria == 'limpeza':
      if qnt_atual < 30:
        print(f'solicitar {nome_produto} a equipe de compras, temos apenas {qnt_atual} em estoque')

else:
  print('não existe essa categoria')